### ISSUE TITLE
ping from docker doesn't seem to work.

### ISSUE THREAD

**Issue by Capusjon** [shukriadams/arewedown#19]
I configured a few simple ping tests. Docker log and log inside config folder all give me this error:

```
{"message":"Unhandled exception running \"net.ping\"","stack":"Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...\n    at ChildProcess.<anonymous> (/etc/arewedown/node_modules/ping/lib/ping-promise.js:61:19)\n    at Object.onceWrapper (events.js:421:26)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","level":"error","timestamp":"2022-05-01T16:27:29.917Z"}
{"message":"Unhandled exception running \"net.ping\"","stack":"Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...\n    at ChildProcess.<anonymous> (/etc/arewedown/node_modules/ping/lib/ping-promise.js:61:19)\n    at Object.onceWrapper (events.js:421:26)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at runNextTicks (internal/process/task_queues.js:66:3)\n    at processTimers (internal/timers.js:494:9)","level":"error","timestamp":"2022-05-01T16:28:00.011Z"}
{"message":"Unhandled exception running \"net.ping\"","stack":"Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...\n    at ChildProcess.<anonymous> (/etc/arewedown/node_modules/ping/lib/ping-promise.js:61:19)\n    at Object.onceWrapper (events.js:421:26)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at runNextTicks (internal/process/task_queues.js:66:3)\n    at processTimers (internal/timers.js:494:9)","level":"error","timestamp":"2022-05-01T16:29:00.009Z"}
{"message":"Unhandled exception running \"net.ping\"","stack":"Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...\n    at ChildProcess.<anonymous> (/etc/arewedown/node_modules/ping/lib/ping-promise.js:61:19)\n    at Object.onceWrapper (events.js:421:26)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","level":"error","timestamp":"2022-05-01T17:26:36.354Z"}
{"message":"Unhandled exception running \"net.ping\"","stack":"Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...\n    at ChildProcess.<anonymous> (/etc/arewedown/node_modules/ping/lib/ping-promise.js:61:19)\n    at Object.onceWrapper (events.js:421:26)\n    at ChildProcess.emit (events.js:314:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)\n    at onErrorNT (internal/child_process.js:470:16)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\n    at runNextTicks (internal/process/task_queues.js:66:3)\n    at processTimers (internal/timers.js:494:9)","level":"error","timestamp":"2022-05-01T17:27:00.029Z"}
```
This is the config:

```
watchers:
      Pihole-raspberryPi:
          test: net.ping
          host: 10.100.10.251

          # optional
          timeout: 10

```

Am I missing something? What could be the problem?

Kind regards

**Comment by Capusjon** [comment]
I don't know what went wrong but I fixed it by installing iputils-ping inside the docker..

now ping seems to work

**Comment by Capusjon** [comment]
I do have an other question though;

Now it checks every minute if the IP is up or not, can I edit this value to let's say every 10 minutes?

**Comment by Capusjon** [comment]
> I do have an other question though;
> 
> Now it checks every minute if the IP is up or not, can I edit this value to let's say every 10 minutes?

Sorry found that as well. All acording to Cron Syntax

interval: "*/10 * * * *" 

Thanks for the container though. Does exactly what I need it to do 👍 

Issue for the ping remains though, I assume this should be working without me installing annything inside the container.
Kind regards,
Colin

**Comment by shukriadams** [comment]
Thanks for reporting, I'll look into the ping issue ASAP.

**Comment by Capusjon** [comment]
@shukriadams i'm running both. 2 machines one is x64 other is a rasspberry pi. Both have the same issues and are fixable by installing iputils-ping

**Comment by shukriadams** [comment]
Yep, adding iputils-ping fixed it. [92792e](https://github.com/shukriadams/arewedown/commit/92792e27996f49ca0dda5bc736302b73ac69c399) will be in the next release.
